#!/bin/bash
user=$(/bin/ls /Users | /usr/bin/awk '$1 != "Shared" && $1 != ".localized" && $1 != "lab" {print $1}' | /usr/bin/tr -d "\n")
/usr/bin/sed -i '' "s/CURRENTUSER=/CURRENTUSER=$user/" /private/var/tmp/depNotify.sh
/bin/chmod a+x /var/tmp/depNotify.sh
/bin/chmod 644 /Library/LaunchDaemons/edu.trinity.launch.plist
/usr/sbin/chown root:wheel /Library/LaunchDaemons/edu.trinity.launch.plist
/bin/launchctl bootstrap system /Library/LaunchDaemons/edu.trinity.launch.plist